spring.application.name=fakejobdetector

# PostgreSQL (Neon Database Settings)
spring.datasource.url=jdbc:postgresql://ep-polished-silence-azmy6k89-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_64OHaLXjDwqo&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Disable H2 Console (Not needed for PostgreSQL)
spring.h2.console.enabled=false