spring.application.name=fakejobdetector

# PostgreSQL (Neon Database Settings)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Disable H2 Console (Not needed for PostgreSQL)
spring.h2.console.enabled=false